# Generated by Django 5.0 on 2026-07-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='created',
        ),
    ]
